// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable CS8981

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.ServiceExample.ServiceApplication.T4Files
namespace ISI.ServiceExample.ServiceApplication
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Files
	{
		public static string __root = "~/";
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Files)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class wwwroot
		{
			public static string _root()
			{
				return string.Format("{0}wwwroot/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class JavaScripts
			{
				public static string _root()
				{
					return string.Format("{0}JavaScripts/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Files.wwwroot.JavaScripts._root());
					}
				
					public static readonly string _Layout_js = _root() + "_Layout.js";
				}
				public static readonly string _Layout_js = _root() + "_Layout.js";
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Files.wwwroot.JavaScripts._root());
					}
				
					public static readonly string _Layout_js = _root() + "_Layout.js";
					public static readonly string Index_js = _root() + "Index.js";
				}
				public static readonly string Index_js = _root() + "Index.js";
			}
			public static readonly string _Shared = _root() + "_Shared";
			public static readonly string Public = _root() + "Public";
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class lib
			{
				public static string _root()
				{
					return string.Format("{0}lib/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class bootstrap
				{
					public static string _root()
					{
						return string.Format("{0}bootstrap/", T4Files.wwwroot.lib._root());
					}
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Files.wwwroot.lib.bootstrap._root());
						}
					
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class css
						{
							public static string _root()
							{
								return string.Format("{0}css/", T4Files.wwwroot.lib.bootstrap.dist._root());
							}
						
							public static readonly string bootstrap_css = _root() + "bootstrap.css";
							public static readonly string bootstrap_css_map = _root() + "bootstrap.css.map";
							public static readonly string bootstrap_min_css = _root() + "bootstrap.min.css";
							public static readonly string bootstrap_rtl_css = _root() + "bootstrap.rtl.css";
							public static readonly string bootstrap_grid_css = _root() + "bootstrap-grid.css";
							public static readonly string bootstrap_grid_css_map = _root() + "bootstrap-grid.css.map";
							public static readonly string bootstrap_grid_min_css = _root() + "bootstrap-grid.min.css";
							public static readonly string bootstrap_grid_rtl_css = _root() + "bootstrap-grid.rtl.css";
							public static readonly string bootstrap_reboot_css = _root() + "bootstrap-reboot.css";
							public static readonly string bootstrap_reboot_css_map = _root() + "bootstrap-reboot.css.map";
							public static readonly string bootstrap_reboot_min_css = _root() + "bootstrap-reboot.min.css";
							public static readonly string bootstrap_reboot_rtl_css = _root() + "bootstrap-reboot.rtl.css";
							public static readonly string bootstrap_utilities_css = _root() + "bootstrap-utilities.css";
							public static readonly string bootstrap_utilities_css_map = _root() + "bootstrap-utilities.css.map";
							public static readonly string bootstrap_utilities_min_css = _root() + "bootstrap-utilities.min.css";
							public static readonly string bootstrap_utilities_rtl_css = _root() + "bootstrap-utilities.rtl.css";
						}
						public static readonly string bootstrap_css = _root() + "bootstrap.css";
						public static readonly string bootstrap_grid_css = _root() + "bootstrap-grid.css";
						public static readonly string bootstrap_reboot_css = _root() + "bootstrap-reboot.css";
						public static readonly string bootstrap_utilities_css = _root() + "bootstrap-utilities.css";
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class js
						{
							public static string _root()
							{
								return string.Format("{0}js/", T4Files.wwwroot.lib.bootstrap.dist._root());
							}
						
							public static readonly string bootstrap_js = _root() + "bootstrap.js";
							public static readonly string bootstrap_bundle_js = _root() + "bootstrap.bundle.js";
							public static readonly string bootstrap_esm_js = _root() + "bootstrap.esm.js";
							public static readonly string bootstrap_js_map = _root() + "bootstrap.js.map";
							public static readonly string bootstrap_min_js = _root() + "bootstrap.min.js";
						}
						public static readonly string bootstrap_js = _root() + "bootstrap.js";
					}
					public static readonly string css = _root() + "css";
					public static readonly string js = _root() + "js";
					public static readonly string LICENSE = _root() + "LICENSE";
				}
				public static readonly string dist = _root() + "dist";
				public static readonly string LICENSE = _root() + "LICENSE";
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery
				{
					public static string _root()
					{
						return string.Format("{0}jquery/", T4Files.wwwroot.lib._root());
					}
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Files.wwwroot.lib.jquery._root());
						}
					
						public static readonly string jquery_js = _root() + "jquery.js";
						public static readonly string jquery_min_js = _root() + "jquery.min.js";
					}
					public static readonly string jquery_js = _root() + "jquery.js";
					public static readonly string LICENSE_txt = _root() + "LICENSE.txt";
				}
				public static readonly string LICENSE_txt = _root() + "LICENSE.txt";
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation/", T4Files.wwwroot.lib._root());
					}
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Files.wwwroot.lib.jquery_validation._root());
						}
					
						public static readonly string additional_methods_js = _root() + "additional-methods.js";
						public static readonly string additional_methods_min_js = _root() + "additional-methods.min.js";
						public static readonly string jquery_validate_js = _root() + "jquery.validate.js";
						public static readonly string jquery_validate_min_js = _root() + "jquery.validate.min.js";
					}
					public static readonly string additional_methods_js = _root() + "additional-methods.js";
					public static readonly string jquery_validate_js = _root() + "jquery.validate.js";
					public static readonly string LICENSE_md = _root() + "LICENSE.md";
				}
				public static readonly string LICENSE_md = _root() + "LICENSE.md";
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation_unobtrusive
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation-unobtrusive/", T4Files.wwwroot.lib._root());
					}
				
					public static readonly string jquery_validate_unobtrusive_js = _root() + "jquery.validate.unobtrusive.js";
					public static readonly string jquery_validate_unobtrusive_min_js = _root() + "jquery.validate.unobtrusive.min.js";
					public static readonly string LICENSE_txt = _root() + "LICENSE.txt";
				}
				public static readonly string jquery_validate_unobtrusive_js = _root() + "jquery.validate.unobtrusive.js";
			}
			public static readonly string bootstrap = _root() + "bootstrap";
			public static readonly string jquery = _root() + "jquery";
			public static readonly string jquery_validation = _root() + "jquery-validation";
			public static readonly string jquery_validation_unobtrusive = _root() + "jquery-validation-unobtrusive";
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class StyleSheets
			{
				public static string _root()
				{
					return string.Format("{0}StyleSheets/", T4Files.wwwroot._root());
				}
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Files.wwwroot.StyleSheets._root());
					}
				
					public static readonly string _Layout_css = _root() + "_Layout.css";
				}
				public static readonly string _Layout_css = _root() + "_Layout.css";
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Files.wwwroot.StyleSheets._root());
					}
				
					public static readonly string _Layout_css = _root() + "_Layout.css";
					public static readonly string Index_css = _root() + "Index.css";
				}
				public static readonly string Index_css = _root() + "Index.css";
			}
		}
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Views
		{
			public static string _root()
			{
				return string.Format("{0}Views/", T4Files._root());
			}
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class _Shared
			{
				public static string _root()
				{
					return string.Format("{0}_Shared/", T4Files.Views._root());
				}
			
				public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
			}
			public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class Public
			{
				public static string _root()
				{
					return string.Format("{0}Public/", T4Files.Views._root());
				}
			
				public static readonly string _Layout_cshtml = _root() + "_Layout.cshtml";
				public static readonly string Index_cshtml = _root() + "Index.cshtml";
			}
			public static readonly string Index_cshtml = _root() + "Index.cshtml";
			public static readonly string _ViewImports_cshtml = _root() + "_ViewImports.cshtml";
		}
	}
}
#endregion

#region ISI.ServiceExample.ServiceApplication.T4Links
namespace ISI.ServiceExample.ServiceApplication
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Links
	{
		private static Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> _getContentUrl = null;
		public static Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> GetContentUrl 
		{
			get => _getContentUrl ??= (url, isOriginalUrl) => new global::ISI.Extensions.AspNetCore.ContentUrl(url, isOriginalUrl);
			set => _getContentUrl = value;
		}
	
		[ISI.Extensions.AspNetCore.ContentUrlGeneratorSetter]
		public class ContentUrlGeneratorSetter : global::ISI.Extensions.AspNetCore.IContentUrlGeneratorSetter
		{
			public void SetContentUrlGenerator(Func<string, bool, global::ISI.Extensions.AspNetCore.IContentUrl> setter)
			{
				GetContentUrl = setter;
			}
		}
	
		public static string __root = "~/";
		public static string _root()
		{
			return (__root ??= ISI.Extensions.VirtualFileVolumesFileProvider.GetPathPrefix(typeof(T4Links)));
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class wwwroot
		{
			public static string _root()
			{
				return T4Links._root();
			}
		
			private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
			public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links._root() + "wwwroot", true);
		
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class JavaScripts
			{
				public static string _root()
				{
					return string.Format("{0}JavaScripts/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "JavaScripts", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Links.wwwroot.JavaScripts._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.JavaScripts._root() + "_Shared", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_js => __Layout_js ??= GetContentUrl(_root() + "_Layout.js", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Links.wwwroot.JavaScripts._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.JavaScripts._root() + "Public", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_js => __Layout_js ??= GetContentUrl(_root() + "_Layout.js", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _Index_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl Index_js => _Index_js ??= GetContentUrl(_root() + "Index.js", true);
				}
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class lib
			{
				public static string _root()
				{
					return string.Format("{0}lib/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "lib", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class bootstrap
				{
					public static string _root()
					{
						return string.Format("{0}bootstrap/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "bootstrap", true);
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Links.wwwroot.lib.bootstrap._root());
						}
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.bootstrap._root() + "dist", true);
					
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class css
						{
							public static string _root()
							{
								return string.Format("{0}css/", T4Links.wwwroot.lib.bootstrap.dist._root());
							}
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.bootstrap.dist._root() + "css", true);
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_css => _bootstrap_css ??= GetContentUrl(_root() + "bootstrap.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_css_map = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_css_map => _bootstrap_css_map ??= GetContentUrl(_root() + "bootstrap.css.map", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_min_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_min_css => _bootstrap_min_css ??= GetContentUrl(_root() + "bootstrap.min.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_rtl_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_rtl_css => _bootstrap_rtl_css ??= GetContentUrl(_root() + "bootstrap.rtl.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_grid_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_grid_css => _bootstrap_grid_css ??= GetContentUrl(_root() + "bootstrap-grid.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_grid_css_map = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_grid_css_map => _bootstrap_grid_css_map ??= GetContentUrl(_root() + "bootstrap-grid.css.map", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_grid_min_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_grid_min_css => _bootstrap_grid_min_css ??= GetContentUrl(_root() + "bootstrap-grid.min.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_grid_rtl_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_grid_rtl_css => _bootstrap_grid_rtl_css ??= GetContentUrl(_root() + "bootstrap-grid.rtl.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_reboot_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_reboot_css => _bootstrap_reboot_css ??= GetContentUrl(_root() + "bootstrap-reboot.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_reboot_css_map = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_reboot_css_map => _bootstrap_reboot_css_map ??= GetContentUrl(_root() + "bootstrap-reboot.css.map", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_reboot_min_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_reboot_min_css => _bootstrap_reboot_min_css ??= GetContentUrl(_root() + "bootstrap-reboot.min.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_reboot_rtl_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_reboot_rtl_css => _bootstrap_reboot_rtl_css ??= GetContentUrl(_root() + "bootstrap-reboot.rtl.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_utilities_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_utilities_css => _bootstrap_utilities_css ??= GetContentUrl(_root() + "bootstrap-utilities.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_utilities_css_map = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_utilities_css_map => _bootstrap_utilities_css_map ??= GetContentUrl(_root() + "bootstrap-utilities.css.map", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_utilities_min_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_utilities_min_css => _bootstrap_utilities_min_css ??= GetContentUrl(_root() + "bootstrap-utilities.min.css", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_utilities_rtl_css = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_utilities_rtl_css => _bootstrap_utilities_rtl_css ??= GetContentUrl(_root() + "bootstrap-utilities.rtl.css", true);
						}
						[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
						public static partial class js
						{
							public static string _root()
							{
								return string.Format("{0}js/", T4Links.wwwroot.lib.bootstrap.dist._root());
							}
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.bootstrap.dist._root() + "js", true);
						
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_js = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_js => _bootstrap_js ??= GetContentUrl(_root() + "bootstrap.js", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_bundle_js = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_bundle_js => _bootstrap_bundle_js ??= GetContentUrl(_root() + "bootstrap.bundle.js", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_esm_js = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_esm_js => _bootstrap_esm_js ??= GetContentUrl(_root() + "bootstrap.esm.js", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_js_map = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_js_map => _bootstrap_js_map ??= GetContentUrl(_root() + "bootstrap.js.map", true);
							private static global::ISI.Extensions.AspNetCore.IContentUrl _bootstrap_min_js = null;
							public static global::ISI.Extensions.AspNetCore.IContentUrl bootstrap_min_js => _bootstrap_min_js ??= GetContentUrl(_root() + "bootstrap.min.js", true);
						}
					}
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE => _LICENSE ??= GetContentUrl(_root() + "LICENSE", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery
				{
					public static string _root()
					{
						return string.Format("{0}jquery/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "jquery", true);
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Links.wwwroot.lib.jquery._root());
						}
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.jquery._root() + "dist", true);
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_js => _jquery_js ??= GetContentUrl(_root() + "jquery.js", true);
						private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_min_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_min_js => _jquery_min_js ??= GetContentUrl(_root() + "jquery.min.js", true);
					}
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE_txt = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE_txt => _LICENSE_txt ??= GetContentUrl(_root() + "LICENSE.txt", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "jquery-validation", true);
				
					[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
					public static partial class dist
					{
						public static string _root()
						{
							return string.Format("{0}dist/", T4Links.wwwroot.lib.jquery_validation._root());
						}
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib.jquery_validation._root() + "dist", true);
					
						private static global::ISI.Extensions.AspNetCore.IContentUrl _additional_methods_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl additional_methods_js => _additional_methods_js ??= GetContentUrl(_root() + "additional-methods.js", true);
						private static global::ISI.Extensions.AspNetCore.IContentUrl _additional_methods_min_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl additional_methods_min_js => _additional_methods_min_js ??= GetContentUrl(_root() + "additional-methods.min.js", true);
						private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_validate_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_validate_js => _jquery_validate_js ??= GetContentUrl(_root() + "jquery.validate.js", true);
						private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_validate_min_js = null;
						public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_validate_min_js => _jquery_validate_min_js ??= GetContentUrl(_root() + "jquery.validate.min.js", true);
					}
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE_md = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE_md => _LICENSE_md ??= GetContentUrl(_root() + "LICENSE.md", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class jquery_validation_unobtrusive
				{
					public static string _root()
					{
						return string.Format("{0}jquery-validation-unobtrusive/", T4Links.wwwroot.lib._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.lib._root() + "jquery-validation-unobtrusive", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_validate_unobtrusive_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_validate_unobtrusive_js => _jquery_validate_unobtrusive_js ??= GetContentUrl(_root() + "jquery.validate.unobtrusive.js", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _jquery_validate_unobtrusive_min_js = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl jquery_validate_unobtrusive_min_js => _jquery_validate_unobtrusive_min_js ??= GetContentUrl(_root() + "jquery.validate.unobtrusive.min.js", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _LICENSE_txt = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl LICENSE_txt => _LICENSE_txt ??= GetContentUrl(_root() + "LICENSE.txt", true);
				}
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class StyleSheets
			{
				public static string _root()
				{
					return string.Format("{0}StyleSheets/", T4Links.wwwroot._root());
				}
			
				private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
				public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot._root() + "StyleSheets", true);
			
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class _Shared
				{
					public static string _root()
					{
						return string.Format("{0}_Shared/", T4Links.wwwroot.StyleSheets._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.StyleSheets._root() + "_Shared", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_css => __Layout_css ??= GetContentUrl(_root() + "_Layout.css", true);
				}
				[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
				public static partial class Public
				{
					public static string _root()
					{
						return string.Format("{0}Public/", T4Links.wwwroot.StyleSheets._root());
					}
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl _directory = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Directory => _directory ??= GetContentUrl(T4Links.wwwroot.StyleSheets._root() + "Public", true);
				
					private static global::ISI.Extensions.AspNetCore.IContentUrl __Layout_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl _Layout_css => __Layout_css ??= GetContentUrl(_root() + "_Layout.css", true);
					private static global::ISI.Extensions.AspNetCore.IContentUrl _Index_css = null;
					public static global::ISI.Extensions.AspNetCore.IContentUrl Index_css => _Index_css ??= GetContentUrl(_root() + "Index.css", true);
				}
			}
		}
	}
}
#endregion

